#!/usr/bin/env python3
"""Assemble the Vibetiles plugin from the theme's own files.

The design panel is leaving the theme for a plugin (2026-09-21). While the move
is under way the panel's files stay HERE, in the theme, where they are worked
on every day; the plugin is put together from them, so there is one copy and
nothing can drift. This is the same idea as the kit's `build.mjs --sync`.

    python3 tools/build-plugin.py           build dist/vibetiles.zip and list it
    python3 tools/build-plugin.py --list    list what would ship, build nothing
    python3 tools/build-plugin.py --to DIR  also lay the built plugin out in DIR (its own
                                            repository, ~/Developer/live-design-panel: what is
                                            built here is what is committed there; .git and
                                            README.md in DIR are left alone)

What goes in: plugin/ (the plugin's own file, written by hand) and the COPIED
list below, byte for byte. When a panel file is added to the theme, add it to
COPIED here and to the skip in functions.php (architrave_panel_active).
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import subprocess
import sys
import zipfile
from pathlib import Path

THEME = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(THEME / "tools"))
import php_strip  # noqa: E402  (the shipped PHP without its notes)
SLUG = "vibetiles"
OWN = "plugin"
COPIED = [
    "assets/js/reading-face.js",
    "assets/js/reading-leading.js",
    "assets/js/presets.js",
    "assets/js/reading-panel.js",
    # WHAT A GUEST CANNOT BORROW (0.8.0). The four above name these six as their
    # needs. On Architrave the theme registers all six and the plugin simply
    # names the handles; on any other theme an unregistered dependency makes
    # wp_enqueue_script drop the script without a word, which is why the panel
    # was silently absent there. So they travel with the plugin and it registers
    # them itself when it is a guest (architrave_panel_support_scripts).
    "assets/js/quire.modes.js",
    "assets/js/quire.icons.js",
    "assets/js/quire.reading.js",
    "assets/js/focus-mode.js",
    "assets/js/color-mode.js",
    "assets/js/reading-scale.js",
    "inc/duotone-filter.php",  # the four SVG filters, shared with the theme (0.9.0)
    "inc/quire-icons.php",  # the icon registry, so the plugin's own door can draw one (2026-09-22)
    "inc/site-styles.php",
    "inc/style-schema.json",
    "inc/style-guide.json",
]
PHP = "/Users/manuelesposito/Library/Application Support/Local/lightning-services/php-8.1.29+0/bin/darwin-arm64/bin/php"

SRC_README = """# The source

The plugin's files as they are written, before the build touches them. The
build (`tools/build-plugin.py`) does two things to what ships: it strips the
working comments out of the PHP and JavaScript (this folder keeps them), and
it stamps the version into `readme.txt` and the loader. Nothing is minified
or renamed, here or in the build.

What is here:

- `*.php`, `inc/`, `assets/js/`, `assets/css/door.css` - the plugin as
  authored, comments and all.
- `assets/css/panel-page.css` - the hand-written half of that sheet; the
  build appends generated size ladders to it.
- `tools/` - the build scripts themselves.

What is not here: the five generated stylesheets at the repository root
(`panel.css`, `panel-guest.css`, `panel-tokens.css`, `panel-parts.css`,
`panel-shell.css`). The panel grew inside the Architrave theme, and those
sheets are cut rule for rule out of the theme's stylesheet by
`tools/split_style.py` and `tools/panel-tokens.py` (the guest variants add a
guard so a host theme's own button and field rules cannot reach into the
panel). The theme is not public, so its stylesheet is not either; the cut
sheets at the root are the plugin's stylesheets of record, plain unminified
CSS, and this folder's tools are exactly what produced them.

`font-files.json` and `assets/js/font-library.js` are generated by
`tools/font-library.py` from a one-line-per-face list, with every download
address pinned to an exact version.
"""


def keyframes(names):
    """The @keyframes the panel's own rules name, lifted from style.css.

    THE SPLITTER CARRIES RULES, NOT AT-RULES. `split_style.shell` keeps every
    rule whose selector names a class the panel prints, and `@keyframes` has no
    selector, so an animation the panel asks for arrived without its drawing:
    measured 2026-09-22 on a guest, `animation-name: reading-panel-rise` was set
    on every row of the panel and nothing moved, because the browser had never
    been told what that name means. Copied here at build time rather than by
    hand, so the two cannot drift.

    THE LIST GREW WHEN THE ROW-BY-ROW REVEAL WENT (2026-09-22, the roll). That
    animation was the only name here, and asking for it after it was gone made
    the build stop, which is the guard doing its job. The four names that took
    its place were all in the same position it had been in: the panel asks for
    them and no guest had ever been told what they mean, so the sheet turning
    between levels and the opening on a phone were both still.
    """
    half = (THEME / "style.css").read_text()
    out = []
    for name in names:
        at = half.find("@keyframes " + name)
        if at == -1:
            print(f"style.css has no @keyframes {name}, which the panel's reveal needs")
            raise SystemExit(1)
        depth, end = 0, at
        for i in range(at, len(half)):
            if half[i] == "{":
                depth += 1
            elif half[i] == "}":
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break
        out.append(half[at:end])
    return ("\n" + "\n".join(out) + "\n") if out else ""


def stripper():
    """The theme zip's own comment stripper, so the plugin's scripts reach the
    server exactly as the theme's did: the reasoning stays in the repository."""
    spec = importlib.util.spec_from_file_location("build_dist", THEME / "tools" / "build-dist.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.strip_comments


def php_stripped(p: Path) -> bytes:
    """The shipped PHP without its working notes (2026-09-25, for wordpress.org:
    the comments quote private conversations and name files only this
    repository has). tools/php_strip.py does it, for the theme and Extras too;
    without a PHP binary the file ships whole, which is only ever a local build."""
    if not Path(PHP).is_file():
        return p.read_bytes()
    return php_strip.php(p)


def fonts() -> list[tuple[Path, str]]:
    """The font files plugin/fonts.json names, from the theme repo's
    assets/fonts/webfonts (where the lab and the kit still read them), and
    every licence text beside them: the OFL travels with its face."""
    import json

    data = json.loads((THEME / OWN / "fonts.json").read_text())
    names = sorted({src.split("/")[-1] for fam in data["fontFamilies"] for face in fam["fontFace"] for src in face["src"]})
    out = [(THEME / "assets/fonts/webfonts" / n, f"fonts/{n}") for n in names]
    # Every licence beside a face that travels. Newsreader and Inter joined
    # fonts.json in 0.9.0, so their licences travel too: on a theme that is not
    # Architrave neither face exists, and without them the panel drew itself in
    # the system sans and the default reading face fell back to Georgia.
    out += [(p, f"fonts/{p.name}") for p in sorted((THEME / "assets/fonts").glob("*-OFL.txt"))]
    return out


ASSEMBLED = {"assets/css/panel-page.css"}  # written below, hand-written head plus a generated tail


def members() -> list[tuple[Path, str]]:
    own = sorted(
        p
        for p in (THEME / OWN).rglob("*")
        if p.is_file() and not p.name.startswith(".") and str(p.relative_to(THEME / OWN)) not in ASSEMBLED
    )
    out = [(p, str(p.relative_to(THEME / OWN))) for p in own]
    out += [(THEME / rel, rel) for rel in COPIED]
    out += fonts()
    return out


LADDER = re.compile(r'^:root\[data-reading="([a-z]+)"\]$')
TOP = re.compile(r"([0-9.]+)px\s*\)\s*$")
# What the reading stepper moves, and the token that says by how much. Measured
# on Architrave: pressing Larger twice takes the title 64 → 72, an h2 36 → 47 and
# a paragraph 22 → 28, so each part of the article climbs its own ladder and a
# guest that moved the paragraphs alone was doing a different thing (Manuel,
# 2026-09-22: "that Double A works differently than Elmastudio").
RUNGS = ["--text-article-title"] + ["--text-article-h%d" % i for i in range(1, 7)] + ["--text-reading-body"]


def ladder(theme_half: list, found: dict) -> str:
    """The reading stepper, as RATIOS of what the host rests at, one per part.

    The theme's ladder is absolute: a 22px paragraph at Default, 14 at Tiny, 36
    at Huge. Copied as it stands onto a theme whose paragraph is 16px the stepper
    stops being a stepper, because Default would be the host's 16 while the rungs
    below it sit at 14, 16 and 18 and pressing Smaller would make the text
    bigger. Each rung is divided by Default's and spent as a multiplier, so the
    host's own size stays the middle of the reader's ladder and every part of the
    article climbs at the rate Architrave gives it. Read from style.css at build
    time: an eighth rung, or a heading level that moves, arrives on its own.
    """
    import split_style as S

    steps: dict[str, dict[str, float]] = {}

    def walk(items: list) -> None:
        for item in items:
            if item[0] == "rule":
                names = [m.group(1) for m in (LADDER.match(sel.strip()) for sel in S.split_selectors(item[1])) if m]
                if names:
                    for prop, value in re.findall(r"(--[\w-]+)\s*:\s*([^;]+)", item[2]):
                        if prop not in RUNGS:
                            continue
                        hit = TOP.search(value.strip())
                        if hit:
                            for name in names:
                                steps.setdefault(name, {})[prop] = float(hit.group(1))
            elif item[0] == "at":
                walk(item[2])

    walk(theme_half)
    ground: dict[str, float] = {}
    for prop in RUNGS:
        if prop in steps.get("default", {}):
            ground[prop] = steps["default"][prop]
        elif prop in found:
            hit = TOP.search(found[prop].strip())
            if hit:
                ground[prop] = float(hit.group(1))
    missing = [p for p in RUNGS if p not in ground]
    if missing or "default" not in steps:
        raise SystemExit("the reading ladder moved: no resting size for " + ", ".join(missing or ["(the default rung)"]))

    def key(prop: str) -> str:
        return prop.replace("--text-article-", "").replace("--text-reading-body", "body")

    out = [
        "",
        "/* THE READING STEPPER, as ratios of the host theme's own resting sizes,",
        "   one for each part of the article. GENERATED by tools/build-plugin.py from",
        "   style.css (Default is the host's own, so it has no rule). assets/js/",
        "   guest-size.js spends them, because a stylesheet cannot ask an element how",
        "   big it already is. */",
    ]
    # THE RUNGS THEMSELVES, FOR A LOOK (2026-09-22). Under any tile but the
    # theme's own, guest-size.js starts each part from Architrave's resting size
    # rather than the host's, so Standard on a stranger's theme has Standard's
    # scale and not only its faces. Gated on data-chosen, which is that tile.
    out.append(':root[data-chosen] { %s }' % " ".join("--panel-rung-%s: %gpx;" % (key(prop), ground[prop]) for prop in RUNGS))
    for rung in sorted(steps, key=lambda r: steps[r].get("--text-reading-body", 0)):
        if rung == "default":
            continue
        parts = []
        for prop in RUNGS:
            if prop in steps[rung] and ground.get(prop):
                parts.append("--panel-step-%s: %.4g;" % (key(prop), steps[rung][prop] / ground[prop]))
        if parts:
            out.append(':root[data-reading="%s"] { %s }' % (rung, " ".join(parts)))
    return "\n".join(out) + "\n"


GATE = (":root[data-", ":root:is([data-", ":root:not([data-")


def gated(css: str, exempt: set | None = None) -> list[str]:
    """Every selector of the role table must begin with a dial on the root.

    THIS IS THE WHOLE SAFETY ARGUMENT of panel-page.css and the only one of the
    guest sheets that can touch the page it landed on. A rule that is not gated
    applies to a stranger's theme the moment the plugin is switched on, which is
    the one thing a guest must never do. Checked here rather than promised in a
    comment, because a comment does not fail a build. The rules lifted word for
    word out of the theme are the named exception: they are inert by VALUE, and
    Architrave ships them ungated on every page for the same reason.
    """
    import split_style as S

    return [
        sel.strip()
        for item in S.parse(S.strip_comments(css))
        if item[0] == "rule"
        for sel in S.split_selectors(item[1])
        if not sel.strip().startswith(GATE) and re.sub(r"\s+", " ", sel.strip()) not in (exempt or set())
    ]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--to", metavar="DIR")
    args = ap.parse_args()

    # A FULL EXPORT MUST SURVIVE THE ROUTE'S CLEANER (2026-09-26): the export
    # outgrew the cleaner's key cap and every publish failed without a word.
    probe = subprocess.run([sys.executable, str(THEME / "tools" / "check-site-styles.py")], cwd=THEME)
    if probe.returncode:
        return probe.returncode
    # NO THEME RULE MAY LOSE TO THE PLUGIN'S SHEET BY LOAD ORDER ALONE (2026-10-01):
    # Book's block beat "Justified text: off" on every site, never on the test site.
    order = subprocess.run([sys.executable, str(THEME / "tools" / "check-split-order.py")], cwd=THEME)
    if order.returncode:
        return order.returncode

    files = members()
    missing = [rel for p, rel in files if not p.is_file()]
    if missing:
        print("missing in the theme: " + ", ".join(missing))
        return 1
    if Path(PHP).is_file():
        for p, rel in files:
            if p.suffix == ".php":
                r = subprocess.run([PHP, "-l", str(p)], capture_output=True, text=True)
                if r.returncode:
                    print(r.stdout + r.stderr)
                    return 1
    else:
        print("php not found, nothing linted")

    total = 0
    for p, rel in files:
        total += p.stat().st_size
        print(f"  {p.stat().st_size:>8}  {SLUG}/{rel}")
    print(f"  {total:>8}  in {len(files)} files")
    if args.list:
        return 0

    dist = THEME / "dist"
    dist.mkdir(exist_ok=True)
    target = dist / f"{SLUG}.zip"
    strip = stripper()
    sys.path.insert(0, str(THEME / "tools"))
    import split_style  # the plugin's half of style.css

    _theme_half_text, plugin_half = split_style.split((THEME / "style.css").read_text())
    _theme_half, _ = split_style.divide(split_style.parse(split_style.strip_comments((THEME / "style.css").read_text())))
    panel_css = (
        "/* Vibetiles: the design panel's interface and every style but Standard.\n"
        "   GENERATED by the theme's tools/build-plugin.py from the theme's style.css\n"
        "   (tools/split_style.py says which rules). Do not edit; the reasoning is in style.css. */\n"
        + plugin_half
    )
    # THE SAME SHEET, BEHIND THE GUARD, FOR A GUEST (0.11.47): every rule that
    # draws the panel one ID heavier (split_style.guarded), so a theme's own
    # `button` and `input` rules cannot reach into it. Architrave keeps panel.css.
    guest_css = (
        "/* Vibetiles: panel.css as a guest gets it, every rule that draws the\n"
        "   panel one ID heavier (see split_style.GUARD). GENERATED; do not edit. */\n"
        + split_style.write(split_style.guarded(split_style.parse(split_style.strip_comments(plugin_half)), only_panel=True))
        + "\n"
    )
    # THE VALUES A GUEST DRAWS ITSELF WITH (0.8.0). panel.css names properties
    # that only the theme underneath defines; on a stranger's theme they resolve
    # to nothing. This is Standard's resting value for each of them, loaded
    # before panel.css and only where the plugin is a guest.
    import importlib.util

    spec = importlib.util.spec_from_file_location("panel_tokens", THEME / "tools" / "panel-tokens.py")
    panel_tokens = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(panel_tokens)
    found = panel_tokens.collect()
    keep = panel_tokens.rooms_close(found, panel_tokens.close_over(panel_tokens.wanted(), found))
    tokens_css = panel_tokens.sheet(found, keep, panel_tokens.rooms("", keep))

    # THE PANEL'S OWN FRAME (0.8.0). The rules that give the panel its sheet, its
    # scrim and its two sides name only the classes the tiny panel wears, so the
    # splitter leaves them with the theme, which still needs them when it stands
    # alone. A guest has no theme to take them from: without this the panel
    # opened as a plain block at the foot of a stranger's page.
    shell_css = (
        "/* Vibetiles: the panel's own frame, which on Architrave belongs to the\n"
        "   theme (the tiny panel wears it too). GENERATED by tools/build-plugin.py from\n"
        "   the theme's style.css; loaded only where the plugin is a guest. */\n"
        + split_style.write(split_style.guarded(split_style.shell(_theme_half)))
        + keyframes(["reading-in", "reading-turn", "reading-turn-forward", "reading-turn-back"])
        + "\n"
    )

    # THE DESIGN-SYSTEM PARTS THE PANEL WEARS (0.8.0). Its buttons, segmented
    # rows and sheet are QDS components, drawn by a sheet a guest never gets.
    # split_style.parts keeps only the rules every branch of which requires one
    # of the four class names the panel prints, so nothing here can reach the
    # guest's own page.
    # THE FLOOR UNDER EVERY COMPONENT (0.9.0). Two rules in quire.css are global
    # and therefore belong to no component, so split_style.parts cannot see them:
    # border-box, and the focus ring. Architrave has both from the QDS sheet. A
    # guest had neither, and it showed: every row on a role's page was 16px wider
    # than the panel, because a row is `width:100%` plus 8px of padding either
    # side and under content-box that is the panel's width plus sixteen. Scoped
    # to what the panel prints, so they cannot reach the page it landed on.
    floor_css = """.reading-panel,
.reading-panel *,
.reading-panel *::before,
.reading-panel *::after,
.architrave-panel-opener,
.architrave-panel-opener * {
\tbox-sizing: border-box;
}
.reading-panel :focus-visible,
.architrave-panel-opener:focus-visible {
\toutline: var(--focus-ring-width) solid var(--focus);
\toutline-offset: var(--focus-ring-offset);
}
/* THE PANEL'S OWN FIELDS ANSWER THE POINTER (Manuel, 2026-09-22, at the paste
   box: "fix that placeholder text and make sure that input field doesn't have
   the right hover or on-click or active state"). It did not have one. A field
   on Architrave takes its rest, its hover and its focus from rules in style.css
   that name `.quire-input` under `body`; not one of them carries a dial, so the
   splitter keeps them all with the theme and a guest's panel received a box that
   never moved. The three states are written here instead, where the panel's own
   floor is, and marked important because the page they land on is a stranger's
   and its own field rules are not ours to predict.
   The placeholder goes up one rung, from the subtle ink to the secondary: on the
   panel's own dark surface the subtle rung measured 3.1:1, which is a hint that
   has to be hunted for. */
.reading-panel :is(.quire-input, .quire-textarea, input[type="text"], input[type="search"], textarea) {
\ttransition: border-color var(--motion-duration-fast, 120ms) ease, background-color var(--motion-duration-fast, 120ms) ease;
}
.reading-panel :is(.quire-input, .quire-textarea, input[type="text"], input[type="search"], textarea)::placeholder {
\tcolor: var(--text-secondary);
\topacity: 1;
}
.reading-panel :is(.quire-input, .quire-textarea, input[type="text"], input[type="search"], textarea):hover:not(:focus) {
\tborder-color: var(--text-secondary) !important;
\tbackground-color: var(--surface-hover) !important;
}
.reading-panel :is(.quire-input, .quire-textarea, input[type="text"], input[type="search"], textarea):focus {
\tborder-color: var(--text-secondary) !important;
\toutline: var(--focus-ring-width) solid var(--focus) !important;
\toutline-offset: var(--focus-ring-offset) !important;
}
"""
    parts_css = (
        "/* Vibetiles: the design-system components the panel wears (its buttons,\n"
        "   its segmented rows, its sheet), and the floor they all stand on. GENERATED by\n"
        "   tools/build-plugin.py from the theme's assets/css/quire.css; loaded only where\n"
        "   the plugin is a guest. */\n"
        + split_style.GUARD_FLOOR
        + split_style.write(split_style.guarded(split_style.parse(split_style.strip_comments(floor_css))))
        + "\n"
        + split_style.write(split_style.guarded(split_style.parts(split_style.parse(split_style.strip_comments((THEME / "assets" / "css" / "quire.css").read_text())))))
        + "\n"
    )

    # THE READER'S CHOICES, SPENT ON CORE MARKUP (0.9.0). The role table with a
    # second address: hand-written in plugin/assets/css/panel-page.css, because
    # a guest carries the reader's dials and not Architrave's design, with the
    # size stepper's rungs read out of style.css and appended so they cannot go
    # stale.
    page_src = THEME / OWN / "assets" / "css" / "panel-page.css"
    lift, lost = split_style.lifted(_theme_half)
    if lost:
        print("style.css no longer has these rules, which the picture looks need:")
        for sel in lost:
            print("   " + sel)
        return 1
    page_css = (
        page_src.read_text()
        + ladder(_theme_half, found)
        + "\n/* THE RULES THAT SPEND A DIAL BUT CARRY NONE, copied word for word from the\n"
        "   theme's style.css by tools/build-plugin.py (split_style.LIFTED). Their\n"
        "   selectors are already core WordPress, so there is nothing to re-point; the\n"
        "   splitter left them behind only because a rule that spends a value names no\n"
        "   dial. They are inert until a look is chosen, by value rather than by a gate:\n"
        "   --surface-layer rests at none and --picture-filter at none, and Architrave\n"
        "   ships them ungated on every page for the same reason. */\n"
        + split_style.write(lift)
        + "\n"
    )

    loose = gated(page_css, {re.sub(r"\s+", " ", sel.strip()) for sel in split_style.LIFTED})
    if loose:
        print("panel-page.css has " + str(len(loose)) + " selector(s) that are not gated on a dial:")
        for sel in loose:
            print("   " + sel[:100])
        return 1

    # THE READ ME SAYS THE HEADER'S VERSION (2026-09-25, for wordpress.org).
    # `Stable tag` in readme.txt must equal the plugin header's Version, and a
    # tag typed twice is a tag that can disagree with itself: the source keeps
    # a placeholder and the build writes the header's number over it.
    version = re.search(r"\*\s*Version:\s*([0-9.]+)", (THEME / OWN / f"{SLUG}.php").read_text()).group(1)

    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as z:
        for p, rel in files:
            data = php_stripped(p) if p.suffix == ".php" else strip(p, p.read_bytes())
            if rel == "readme.txt":
                data = re.sub(rb"(?m)^Stable tag: .*$", b"Stable tag: " + version.encode(), data, count=1)
                if b"WPORG-USERNAME" in data:
                    print("NOTE readme.txt still says WPORG-USERNAME; put the real wordpress.org username in before submitting")
            elif rel == f"{SLUG}.php":
                data = data.replace(b"'ARCHITRAVE_PANEL_VERSION', '0.0.0'", b"'ARCHITRAVE_PANEL_VERSION', '" + version.encode() + b"'")
            z.writestr(f"{SLUG}/{rel}", data)
        z.writestr(f"{SLUG}/assets/css/panel.css", panel_css)
        z.writestr(f"{SLUG}/assets/css/panel-guest.css", guest_css)
        z.writestr(f"{SLUG}/assets/css/panel-tokens.css", tokens_css)
        z.writestr(f"{SLUG}/assets/css/panel-parts.css", parts_css)
        z.writestr(f"{SLUG}/assets/css/panel-shell.css", shell_css)
        z.writestr(f"{SLUG}/assets/css/panel-page.css", page_css)
    print(f"  {len(panel_css):>8}  {SLUG}/assets/css/panel.css (cut from style.css)")
    print(f"  {len(tokens_css):>8}  {SLUG}/assets/css/panel-tokens.css (tools/panel-tokens.py)")
    print(f"  {len(parts_css):>8}  {SLUG}/assets/css/panel-parts.css (the QDS parts it wears, for guests)")
    print(f"  {len(shell_css):>8}  {SLUG}/assets/css/panel-shell.css (the panel's frame, for guests)")
    print(f"  {len(guest_css):>8}  {SLUG}/assets/css/panel-guest.css (panel.css behind the guard, for guests)")
    print(f"  {len(page_css):>8}  {SLUG}/assets/css/panel-page.css (the role table, for guests)")
    print(f"wrote {target.relative_to(THEME)} ({target.stat().st_size} bytes)")
    if args.to:
        import shutil

        dest = Path(args.to).expanduser()
        dest.mkdir(parents=True, exist_ok=True)
        for child in dest.iterdir():
            if child.name in (".git", ".github", "README.md", "LICENSE", ".gitignore", ".wporg-assets"):
                continue  # .wporg-assets: the directory's screenshots/banner/icon, which live in SVN's assets/, never in the zip
            shutil.rmtree(child) if child.is_dir() else child.unlink()
        with zipfile.ZipFile(target) as z:
            for name in z.namelist():
                rel = name.split("/", 1)[1]
                if not rel:
                    continue
                out = dest / rel
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_bytes(z.read(name))
        # THE SOURCE BESIDE THE BUILD (2026-09-25, for wordpress.org). The
        # repository is public source, not withheld build output: src/ carries
        # the PHP and JS exactly as authored, comments and all, plus the tools
        # that turn them into what ships, and says what each generated sheet
        # is cut from. The shipped CSS itself is the plugin's stylesheet of
        # record: plain unminified rules, generated rule for rule.
        src = dest / "src"
        for p, rel in files:
            if p.suffix in (".php", ".js") or rel in ("readme.txt", "assets/css/door.css"):
                out = src / rel
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_bytes(p.read_bytes())
        (src / "assets" / "css").mkdir(parents=True, exist_ok=True)
        (src / "assets" / "css" / "panel-page.css").write_bytes((THEME / OWN / "assets" / "css" / "panel-page.css").read_bytes())
        (src / "tools").mkdir(exist_ok=True)
        for tool in ("build-plugin.py", "split_style.py", "panel-tokens.py", "font-library.py", "compile-po.py"):
            (src / "tools" / tool).write_bytes((THEME / "tools" / tool).read_bytes())
        (src / "README.md").write_text(SRC_README)
        print(f"laid out in {dest} (with src/)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
